"""``ventri stubgen``: typed ``ctx.<service>`` attributes (DESIGN.md 4.2).

Scans plugins -- the ``ventri.plugins`` entry points plus any ``--module`` --
for named ``provides`` declarations (``provides={"llm": ModelProvider}``) and
writes ``ventri_stubs.pyi``::

    class Ctx(Context):
        llm: ModelProvider

plus a runtime ``ventri_stubs.py`` (``Ctx = Context``) so ``from ventri_stubs
import Ctx`` works at run time. Annotate plugins with ``ctx: Ctx`` to get
completion and pyright/mypy checking; runtime behaviour is unchanged
(``Context.__getattr__`` looks the name up).

Rules: only string names that are identifiers, not keywords and not existing
``Context`` attributes become attributes (others are reported as skipped); a
name provided with different types by several plugins becomes a union and is
reported; key types that cannot be imported by name (local classes, typing
constructs) are written as ``Any``.
"""
from __future__ import annotations

import importlib
import inspect
import keyword
from dataclasses import dataclass, field
from importlib.metadata import entry_points
from pathlib import Path
from types import ModuleType
from typing import Any

from ventri import Context
from ventri.plugin import describe

HEADER = "# Generated by `ventri stubgen`; do not edit. Re-run after adding plugins.\n"


@dataclass
class StubResult:
    attrs: dict[str, list[str]] = field(default_factory=dict)  # name -> type expressions
    sources: dict[str, list[str]] = field(default_factory=dict)  # name -> plugin names
    imports: set[tuple[str, str]] = field(default_factory=set)  # (module, name)
    warnings: list[str] = field(default_factory=list)

    def pyi(self) -> str:
        uses_any = any("Any" in t for ts in self.attrs.values() for t in ts)
        lines = [HEADER, *(["from typing import Any", ""] if uses_any else []), "from ventri import Context"]
        for mod, name in sorted(self.imports):
            lines.append(f"from {mod} import {name}")
        lines += ["", "", "class Ctx(Context):",
                  '    """Context with typed service attributes (one per named ``provides``)."""', ""]
        if not self.attrs:
            lines.append("    pass")
        for name in sorted(self.attrs):
            types = self.attrs[name]
            src = ", ".join(self.sources[name])
            lines.append(f"    {name}: {' | '.join(types)}  # from {src}")
        return "\n".join(lines) + "\n"

    @staticmethod
    def runtime() -> str:
        return (HEADER + '"""Runtime twin of ventri_stubs.pyi: type checkers read the .pyi."""\n'
                "from ventri import Context as Ctx\n\n__all__ = [\"Ctx\"]\n")


def _type_expr(t: Any, res: StubResult) -> str:
    if isinstance(t, str):
        return "Any"
    if not inspect.isclass(t):
        return "Any"
    mod, qual = t.__module__, t.__qualname__
    if mod == "builtins":
        return qual
    if "<locals>" in qual or mod == "__main__":
        return "Any"
    top = qual.split(".")[0]
    alias = top
    res.imports.add((mod, top))
    return alias + qual[len(top):]


def collect(targets: list[tuple[str, Any]]) -> StubResult:
    res = StubResult()
    reserved = {n for n in dir(Context) if not n.startswith("__")}
    for origin, target in targets:
        try:
            spec = describe(target)
        except Exception as e:  # noqa: BLE001 - report and keep scanning
            res.warnings.append(f"{origin}: cannot describe plugin ({e})")
            continue
        for name, key in spec.provides.items():
            if not isinstance(name, str) or not name.isidentifier() or keyword.iskeyword(name) \
                    or name.startswith("_"):
                res.warnings.append(f"{origin}: skipped {name!r} (not a usable attribute name)")
                continue
            if name in reserved:
                res.warnings.append(f"{origin}: skipped {name!r} (shadows a Context attribute)")
                continue
            expr = _type_expr(key, res)
            types = res.attrs.setdefault(name, [])
            if expr not in types:
                if types:
                    res.warnings.append(f"{name!r} is provided with different types "
                                        f"({', '.join([*types, expr])}); using a union")
                types.append(expr)
            res.sources.setdefault(name, []).append(spec.name)
    for name, types in res.attrs.items():
        if "Any" in types and len(types) > 1:
            res.attrs[name] = ["Any"]
    return res


def _module_targets(mod: ModuleType) -> list[tuple[str, Any]]:
    out = []
    for attr, obj in vars(mod).items():
        if attr.startswith("_") or getattr(obj, "__module__", None) != mod.__name__:
            continue
        if (inspect.isclass(obj) or callable(obj)) and getattr(obj, "provides", None):
            out.append((f"{mod.__name__}.{attr}", obj))
    return out


def discover(modules: list[str] = (), *, use_entry_points: bool = True) -> list[tuple[str, Any]]:
    """Plugins from the ``ventri.plugins`` entry points and the given modules
    (every public plugin with a ``provides`` declaration)."""
    targets: list[tuple[str, Any]] = []
    if use_entry_points:
        for ep in entry_points(group="ventri.plugins"):
            try:
                obj = ep.load()
            except Exception as e:  # noqa: BLE001 - a broken plugin must not stop stubgen
                targets.append((f"entry point {ep.name}", _Broken(e)))
                continue
            if isinstance(obj, ModuleType):
                targets += _module_targets(obj)
            else:
                targets.append((f"entry point {ep.name}", obj))
    for name in modules:
        targets += _module_targets(importlib.import_module(name))
    return targets


class _Broken:
    def __init__(self, err: Exception) -> None:
        self.err = err

    @property
    def provides(self) -> Any:
        raise self.err


def generate(out_dir: str | Path, modules: list[str] = (), *,
             use_entry_points: bool = True) -> StubResult:
    """Write ``ventri_stubs.pyi`` and ``ventri_stubs.py`` into ``out_dir``."""
    targets = discover(list(modules), use_entry_points=use_entry_points)
    res = StubResult()
    good = []
    for origin, t in targets:
        if isinstance(t, _Broken):
            res.warnings.append(f"{origin}: failed to load ({t.err!r})")
        else:
            good.append((origin, t))
    collected = collect(good)
    collected.warnings[:0] = res.warnings
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "ventri_stubs.pyi").write_text(collected.pyi(), encoding="utf-8")
    (out / "ventri_stubs.py").write_text(StubResult.runtime(), encoding="utf-8")
    return collected
